name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Select the operating system (Ubuntu in this case)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build  # Modify this command based on your project

      - name: Run Tests
        run: npm test  # Modify this command based on your project
